### PR TITLE
Update help.html

### PR DESCRIPTION
**Pull request by AnarchistHoneybun**
minor change I came across when using the web app

### CODE REVIEW

**Review by bbenne10 — APPROVED** [review]

**Comment by bbenne10** [comment]
@ecashin: Do you want me to just go ahead and merge this? Do you want to merge it at all?

**Comment by AnarchistHoneybun** [comment]
> @ecashin: Do you want me to just go ahead and merge this? Do you want to merge it at all?

Oh yes please; I'm a bit new to pull requests so I thought only the author was able to merge

**Comment by bbenne10** [comment]
I thought @ecashin was the one replying and merged too fast -_-

I happen to have collaborator access on this, which allows me the ability to merge.
I was asking the author to confirm if he wanted it merged...
I suppose I'll now just wait to see if he says now and revert in that case?

**Comment by AnarchistHoneybun** [comment]
> I thought @ecashin was the one replying and merged too fast -_-
> 
> I happen to have collaborator access on this, which allows me the ability to merge. I was asking the author to confirm if he wanted it merged... I suppose I'll now just wait to see if he says now and revert in that case?

;-; I'm sorry, I thought this was the author asking (again, too new to this and the @ at the beginning threw me off)

**Comment by ecashin** [comment]
Hi!  Thanks, @AnarchistHoneybun for catching my error and fixing it, and thanks, @bbenne10, for reviewing and merging the fix while I was busy.

**Pull request merged**
